name: Deploy a Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Oracle Cloud
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          host_check: false
          script: |
            cd ~/mg-support-tech
            git pull origin main
            docker compose build --pull
            docker compose up -d
            docker image prune -f
